# This is a sample build configuration for PHP.
# Check our guides at https://confluence.atlassian.com/x/e8YWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
pipelines:
  default:
    - step:
        image: php:5.6.30
        script:
          - apt-get update && apt-get install -y unzip
          - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
          - docker-php-ext-install pdo pdo_mysql
          - composer install
          - php -r "copy('.env.example', '.env');"
          - php artisan key:generate
          - php artisan migrate
          - vendor/bin/phpunit
        services:
          - mariadb
definitions:
  services:
    mariadb:
      image: mariadb
      environment:
        MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
        MYSQL_DATABASE: 'homestead'
        MYSQL_USER: 'homestead'
        MYSQL_PASSWORD: 'secret'